#!/bin/bash

. ./healthcheck_lib

show_uptime()
{
    _show_uptime
}

show_kernelversion()
{
    _show_kernelversion
}

check_network()
{
    CONFIG_PATH="/etc/sysconfig/network*"

    netdevices=$(ls -1 ${CONFIG_PATH} | grep 'ifcfg-.*[0-9]' | \
                sed 's/.*ifcfg-\(.*\)/\1/g')
    
    RETVAL=0
    for dev in ${netdevices};
    do
        ${SUDO} grep -iE "ONBOOT=.?no.?|STARTMODE=(.?manual.?|.?off.?)" \
            $CONFIG_PATH/ifcfg-${dev} >/dev/null 2>&1 && continue

        (/sbin/ifconfig ${dev} | grep -w UP) >/dev/null 2>&1
        [ $? -ge 1 ] && RETVAL=1 && echo " + ${dev} is down."
    done
    
    return $RETVAL
}

check_ntp()
{
    _check_ntp
    return $?
}

_check_multipath_linux()
{
    [ ! -e ${MULTIPATH} ] && return ${CMD_NOT_FOUND}

    ${SUDO} ${MULTIPATH} -l | grep -E "failed|faulty|not loaded"
    [ $? -ge 1 ] && return 0
    return 1
}

_check_multipath_hdlm_linux()
{
    DLNKMGR="${DLNKMGR_LINUX}"
    _check_multipath_hdlm
}

check_multipath()
{
    SUPPORTED_STORAGE="_check_multipath_linux \
        _check_multipath_datapath _check_multipath_hdlm_linux"

    _check_multipath ${SUPPORTED_STORAGE}
    return $?
}

check_mounted_filesystems()
{
    cat /etc/fstab | \
        awk '$2 ~ /^\// && $1 !~ /^#/ && $4 !~ /noauto/ \
        { 
            mpoint = $2
            if (substr($2, length($2)) == "/" && length($2) > 1)
                mpoint = substr($2, 0, length($2)-1)
            print mpoint
        }' | _check_mounted_filesystems
}

check_filesystems_capacity()
{
    ${SUDO} df -lP -x iso9660 | awk '$1 ~ /^\//' | \
        _check_filesystems_capacity
}

check_paging_space()
{
    SWAPON=/sbin/swapon
    FSTAB=/etc/fstab

    available_ps=$(cat ${FSTAB} | \
        awk '$3 ~ /swap/ && $1 !~ /^#/ && $4 !~ /noauto/' | wc -l)
    active_ps=$(${SWAPON} -s | awk 'NR > 1' | wc -l)

    if [[ ${available_ps} -eq 0 ]] ;
    then
        echo " + No paging device(s) in ${FSTAB}"
        return 1
    fi

    if [[ ${available_ps} -ne ${active_ps} ]] ;
    then
        echo " + Paging device(s) not activated"
        return 1
    fi

    ps_use=$(${SWAPON} -s | \
            awk 'BEGIN { tsize = 1; used = 0 }
                NR > 1 { tsize += $(NF-2); used += $(NF-1) }
                END { printf "%d", (used * 100 / tsize) }')
    _check_paging_space_use ${ps_use} || return 1

    return 0
}

